=== uo289097/sewExt/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (tipo+, medio+, inicio*, tiempo+, agencia+, descripcion+, lugarInicio+,
coordenadasInicio+, referencias+, recomendacion+, hito*, hito*, hito*)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT medio (#PCDATA)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT coordenadasInicio (#PCDATA)>
<!ELEMENT referencias (ref+, ref+, ref+)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hito (descripcionHito+, coordenadasHito+, distancia+, fotografias+, video*)>
<!ELEMENT descripcionHito (#PCDATA)>
<!ELEMENT coordenadasHito (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT fotografias (#PCDATA)>
<!ELEMENT video (#PCDATA)>

<!ATTLIST ruta nombre CDATA #REQUIRED>
<!ATTLIST ruta precio CDATA #REQUIRED>
<!ATTLIST tipo tipo CDATA #REQUIRED>
<!ATTLIST medio transporte CDATA #REQUIRED>
<!ATTLIST inicio fecha CDATA #IMPLIED>
<!ATTLIST inicio hora CDATA #IMPLIED>
<!ATTLIST tiempo horas CDATA #REQUIRED>
<!ATTLIST agencia nombre CDATA #REQUIRED>
<!ATTLIST descripcion des CDATA #REQUIRED>
<!ATTLIST lugarInicio emplazamiento CDATA #REQUIRED>
<!ATTLIST coordenadasInicio longitud CDATA #REQUIRED>
<!ATTLIST coordenadasInicio latitud CDATA #REQUIRED>
<!ATTLIST coordenadasInicio altitud CDATA #REQUIRED>
<!ATTLIST ref nom CDATA #REQUIRED>
<!ATTLIST coordenadasHito longitud CDATA #REQUIRED>
<!ATTLIST coordenadasHito latitud CDATA #REQUIRED>
<!ATTLIST coordenadasHito altitud CDATA #REQUIRED>
<!ATTLIST recomendacion nota CDATA #REQUIRED>
<!ATTLIST hito nombreHito CDATA #REQUIRED>
<!ATTLIST descripcionHito desc CDATA #REQUIRED>
<!ATTLIST fotografias ruta CDATA #REQUIRED>

=== uo289097/sewExt/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">

<rutas>
    <ruta nombre="Recorrido histórico privado a pie en Mérida" precio="350,00€">
        <tipo tipo="Arquitectura y monumentos"/>
        <medio transporte="A pie"/>
        <inicio hora="10:00"/>
        <tiempo horas="2h"/>
        <agencia nombre="BlackBuck Travels"/>
        <descripcion des = "Recorrido por los principales emplazamientos turísticos de Mérida"/>
        <lugarInicio emplazamiento="Teatro Romano de Mérida, Anfiteatro, C. Pedro María Plano, Mérida, Spain"/>
        <coordenadasInicio longitud="38.9154955804914" latitud="-6.338398156697899" altitud="217"/>
        <referencias>
            <ref nom="https://www.tripadvisor.es/AttractionProductReview-g227871-d27160207-Private_Historic_Walking_Tour_in_Merida-Merida_Province_of_Badajoz_Extremadura.html"/>
            <ref nom="https://www.getyourguide.es/merida-spain-l146194/merida-private-historic-walking-tour-t586690/?visitor-id=C7GNH34522E165C3TLCWY51UU0CD428C&amp;locale_autoredirect_optout=true"/>
            <ref nom="https://www.blackbucktravels.com/tour/private-historic-walking-tour-in-merida"/>
        </referencias>
        <recomendacion nota="8"/>
        <hito nombreHito="Templo de Diana">
            <descripcionHito desc="Templo que sirvió de fundamento y cubierta de un palacio renacentista del siglo XVI 
                cuyas ruinas aún se pueden contemplar en el lugar, gracias a lo cual se encuentra en un estado de 
                conservación excepcional."/>
            <coordenadasHito longitud="38.91666787787563" latitud="-6.344240045103326" altitud="230"/>
            <distancia>900m</distancia>
            <fotografias ruta="xml/templo-diana.jpg"/>
        </hito>
        <hito nombreHito="Alcazaba árabe">
            <descripcionHito desc="Raro monumento árabe en la antigua ciudad romana rodeada por un extenso 
                foso de agua y palmeras."/>
            <coordenadasHito longitud="38.91640075152674" latitud="-6.346299981549169" altitud="230"/>
            <distancia>300m</distancia>
            <fotografias ruta="xml/alcazaba.jpg"/>
        </hito>
        <hito nombreHito="Basílica de Santa Eulalia">
            <descripcionHito desc="Dedicada a la mártir Santa Eulalia, patrona de la ciudad. La actual iglesia 
            románica fue construida en el siglo XIII sobre las ruinas de una basílica destruida por los árabes."/>
            <coordenadasHito longitud="38.92083150463876" latitud="-6.341483022362118" altitud="222"/>
            <distancia>700m</distancia>
            <fotografias ruta="xml/basilicaSantaEulalia.jpeg"/>
        </hito>
        <hito nombreHito="Acueducto de los Milagros">
            <descripcionHito desc="Obra maestra de ingeniería que habría abastecido de agua a la actual Mérida."/>
            <coordenadasHito longitud="38.92397142102753" latitud="-6.34783871626723" altitud="240"/>
            <distancia>1km</distancia>
            <fotografias ruta="xml/acueducto-milagros.jpg"/>
        </hito>
    </ruta>

    <ruta nombre="Tour oficial por Trujillo" precio="12,50€">
        <tipo tipo="Cultural histórica"/>
        <medio transporte="A pie"/>
        <inicio hora="10:30"/>
        <tiempo horas="2h"/>
        <agencia nombre="Aleguías de turismo"/>
        <descripcion des="Tour por todos los enclaves de Interés Turístico del Conjunto Histórico medieval 
            y renacentista de Trujillo (Cáceres)."/>
        <lugarInicio emplazamiento="Plaza Mayor de Trujillo"/>
        <coordenadasInicio longitud="39.46071160469938" latitud="-5.8811357125364925" altitud="230"/>
        <referencias>
            <ref nom="https://www.tripadvisor.es/AttractionProductReview-g562640-d27479799-OFFICIAL_TOUR_TRUJILLO_Cradle_of_Hispanidad_and_Conquistadors-Trujillo_Province_of.html"/>
            <ref nom="https://www.turismotrujillo.es/"/>
            <ref nom="https://www.aleguias.com/es/activity-card/110/499/5711/tour-oficial-trujillo-cuna-de-la-hispanidad-y-de-conquistadores"/>
        </referencias>
        <recomendacion nota="10"/>
        <hito nombreHito="Plaza Mayor de Trujillo">
            <descripcionHito desc="Flanqueada por torres defensivas y presidida por la famosa 
            estatua ecuestre del Conquistador Francisco Pizarro. "/>
            <coordenadasHito longitud="39.46071160469938" latitud="-5.8811357125364925" altitud="230"/>
            <distancia>0m</distancia>
            <fotografias ruta="xml/trujillo-plaza-mayor.jpg"/>
        </hito>
        <hito nombreHito="Iglesia de Santa María la Mayor">
            <descripcionHito desc="Fue el edifico religioso más relevante de la ciudad, donde 
            están enterrados los principales linajes y los más ilustres Conquistadores que forjaron 
            su pasado medieval"/>
            <coordenadasHito longitud="39.46074792141739" latitud="-5.884551046920885" altitud="240"/>
            <distancia>400m</distancia>
            <fotografias ruta="xml/iglesia-de-santa-maria-la-mayor.jpg"/>
        </hito>
        <hito nombreHito="Aljibe Hispano-Musulman">
            <descripcionHito desc="Aljibe de tracería árabe, con tres naves sobre muros maestros y 
            arcos sostenidos por pilastras, cubiertos con tres bóvedas de medio cañón. Los materiales 
            utilizados en su construcción son sillares de granito, mampostería y argamasa."/>
            <coordenadasHito longitud="39.46009127270497" latitud="-5.883986360413977" altitud="250"/>
            <distancia>120m</distancia>
            <fotografias ruta="xml/aljibe_musulman.jpg"/>
        </hito>
    </ruta>

    <ruta nombre="Ruta en buggy" precio="170,00€">
        <tipo tipo="Paisajística"/>
        <medio transporte="Buggy"/>
        <inicio fecha="martes" hora="09:30"/>
        <tiempo horas="4h"/>
        <agencia nombre="XtremaBuggy rutas y aventuras"/>
        <descripcion des="Los recorridos por la Dehesa Extremeña son especialmente atractivos por ser 
        ésta un ecosistema único en el mundo. Su visita y conocimiento le sorprenderan en todo su recorrido 
        e interpretación."/>
        <lugarInicio emplazamiento="Grupo Xtremabuggy"/>
        <coordenadasInicio longitud="38.15204272139418" latitud="-6.209986151012874" altitud="260"/>
        <referencias>
            <ref nom="https://www.tripadvisor.es/AttractionProductReview-g2449893-d20886745-ROUTE_IN_BUGGY_1_30h-Montemolin_Province_of_Badajoz_Extremadura.html"/>
            <ref nom="https://www.xtremabuggy.com/rutas-excursiones-buggy-quads-caceres/"/>
            <ref nom="https://www.yumping.com/buggies/extremadura"/>
        </referencias>
        <recomendacion nota="9"/>
        <hito nombreHito="Nacimineto del río Viar">
            <descripcionHito desc="Lugar del nacimineto del río Viar, principal afluente del Guadalquivir."/>
            <coordenadasHito longitud="38.05984752910489" latitud="-5.998275425692669" altitud="570"/>
            <distancia>23,9km</distancia>
            <fotografias ruta="xml/rio-viar.jpeg"/>
        </hito>
        <hito nombreHito="Zona de Interés Regional Llanos de Cáceres y Sierra de Fuentes">
            <descripcionHito desc="Área extensa de llanuras con suaves pendientes que se extiende desde Brozas 
            hasta Trujillo"/>
            <coordenadasHito longitud="39.44777884203578" latitud="-6.190741748288021" altitud="510"/>
            <distancia>184km</distancia>
            <fotografias ruta="xml/sierradefuentes.jpg"/>
        </hito>
        <hito nombreHito="Observatorio de aves-Llanos de Cáceres">
            <descripcionHito desc="Zona de observación de un gran número de aves."/>
            <coordenadasHito longitud="39.4773991628095" latitud="-6.189282626309012" altitud="520"/>
            <distancia>5km</distancia>
            <fotografias ruta="xml/observatorio.jpg"/>
        </hito>
    </ruta>
    
</rutas>
